-- CreateTable
CREATE TABLE "Match" (
    "id" SERIAL NOT NULL,
    "tourney_id" TEXT NOT NULL,
    "tourney_name" TEXT NOT NULL,
    "surface" TEXT NOT NULL,
    "draw_size" INTEGER NOT NULL,
    "tourney_level" TEXT NOT NULL,
    "tourney_date" INTEGER NOT NULL,
    "match_num" INTEGER NOT NULL,
    "winner_id" TEXT NOT NULL,
    "winner_seed" INTEGER,
    "winner_entry" TEXT,
    "winner_name" TEXT NOT NULL,
    "winner_hand" TEXT NOT NULL,
    "winner_ht" INTEGER,
    "winner_ioc" TEXT NOT NULL,
    "winner_age" DOUBLE PRECISION NOT NULL,
    "winner_rank" INTEGER,
    "winner_rank_points" INTEGER,
    "loser_id" TEXT NOT NULL,
    "loser_seed" INTEGER,
    "loser_entry" TEXT,
    "loser_name" TEXT NOT NULL,
    "loser_hand" TEXT NOT NULL,
    "loser_ht" INTEGER,
    "loser_ioc" TEXT NOT NULL,
    "loser_age" DOUBLE PRECISION NOT NULL,
    "loser_rank" INTEGER,
    "loser_rank_points" INTEGER,
    "score" TEXT,
    "best_of" INTEGER NOT NULL,
    "round" TEXT NOT NULL,
    "minutes" INTEGER,
    "w_ace" INTEGER,
    "w_df" INTEGER,
    "w_svpt" INTEGER,
    "w_1stIn" INTEGER,
    "w_1stWon" INTEGER,
    "w_2ndWon" INTEGER,
    "w_SvGms" INTEGER,
    "w_bpSaved" INTEGER,
    "w_bpFaced" INTEGER,
    "l_ace" INTEGER,
    "l_df" INTEGER,
    "l_svpt" INTEGER,
    "l_1stIn" INTEGER,
    "l_1stWon" INTEGER,
    "l_2ndWon" INTEGER,
    "l_SvGms" INTEGER,
    "l_bpSaved" INTEGER,
    "l_bpFaced" INTEGER,

    CONSTRAINT "Match_pkey" PRIMARY KEY ("id")
);
